### ISSUE TITLE
Chart can't move when inside a PageView

### ISSUE THREAD

**Issue by nnkti18** [SunPointed/MPFlutterChart#102]
If a chart is inside a PageView, swiping horizontally does not move the chart but instead moving the PageView.
Steps to reproduce:
1: Create a chart inside a PageView. This PageView should have more than 2 pages.
2: Pinch the chart to zoom in
3: Drag the chart to move but can't. If you drag vertically then switch to horizontally, the chart can move normally. However, If you try to move it horizontally first, it will not work.

**Comment by SunPointed** [comment]
I know this, but PageView(or flutter) don't have a nice event dispatch mechanism like android. I search many informations and I still don't know how to make the chart move priority over PageView when chart can move horizontally. Any Ideas?

**Comment by SunPointed** [comment]
Try this days but not work, any ideas?

**Comment by nnkti18** [comment]
> Try this days but not work, any ideas?

I think this has something to do with the OptimizedGestureDetector library because every time the chart's horizontal drag gesture enters the gesture arena always ended with a loss. My temporary workaround will be wrapping the chart in a new GestureDetector and use the painter to translate the chart. But the downside to this is I was not able to fling the chart.

**Comment by SunPointed** [comment]
I try to modify the OptimizedGestureDetector which have multiple GestureRecognizers but only one GestureRecognizer can win in arena, I don't find a solution which can let all GestureRecognizers(all belong to OptimizedGestureDetector ) win together

**Comment by SunPointed** [comment]
finally I find a solution in version 0.2.1, you can see the Scrolling Charts's View Pager Demo to see how to solve this. Though Its worked, it is not perfect yet. The reason is below
I add resolveGestureHorizontalConflict and resolveGestureVerticalConflict to controller to solve chart gesture miss in scrollable views, but set these value to true means in chart area scrollable views will miss gestures. After read a lot about the gesture in flutter, not yet find a solution that can control nest scroll like android fragment in viewpager(when child scroll to the edge the scroll can pass to parent and parent can begin scroll)
