### ISSUE TITLE
zoom in/out multituch

### ISSUE THREAD

**Issue by mfaridi** [SunPointed/MPFlutterChart#14]
problem to zoom in and out multi touch

**Comment by SunPointed** [comment]
This seems cause by the finger scale below 1.0, very close to 0.0, if two fingers to move, so will start from 0.0, this can lead to a great change (because the scale is the current value in addition to previous value). Now each step of the zoom size is added restrictions, I already released to version 0.0.8, you can try.

**Comment by mfaridi** [comment]
I used version 0.0.8
But there is the problem of zooming
It's also not going to be soft around
These problems do not exist in the Android version
**Good luck**

**Comment by SunPointed** [comment]
hi, I replace the GestureDetector, you can use 0.1.0, thanks
